source 'https://rubygems.org'

gem 'rails', '3.2.2'
gem 'sqlite3'
gem 'pg'
gem 'heroku'

# needed for the js runtime environment 
gem 'therubyracer-heroku', '0.8.1.pre3'

# Recomended to use instead of WEBrick
gem 'thin'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'therubyracer'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :test, :development do
    gem 'rspec-rails'
    gem 'guard-rspec'
    gem 'cucumber-rails'
    gem 'factory_girl_rails'
    gem 'database_cleaner'
    gem 'paperclip'
    gem 'railroady'
    gem 'faker'
    # gem 'annotate', '> 2.4.0'
    # gem 'annotate', :git => 'http://github.com/jeremyolliver/annotate_models.git', :branch => 'rake_compatibility'
end

group :production do
    gem 'paperclip'
    gem 'pg'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
